---
- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: eu-west-1
      instance_type: t2.nano
      ami: ami-00035f41c82244dab  # Ubuntu 16.04 LTS
      keypair: key1 # pem file name

  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: default # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         volumes:
            - device_name: /dev/sda1
              volume_type: gp2  #insert the volume code here
              volume_size: 20  #size is in GB
         region: "{{ region }}"
         count: 2 # default
         count_tag:
            Name: web
         instance_tags:
            Name: web
         vpc_subnet_id: subnet-0c228fa0509720bd0
         assign_public_ip: yes
      register: ec2
